catalog:
  "@eslint/js": 9.39.1
  "@types/node": 22.18.12
  eslint: 9.39.1
  prettier: 3.6.2
  rimraf: 6.1.0
  tsdown: 0.16.4
  typescript: 5.9.3
  vitest: 4.0.8

catalogs:
  angular:
    "@angular/common": ^20.3.0
    "@angular/core": ^20.3.0

enableScripts: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@vue/test-utils@*":
    peerDependencies:
      vue: "*"
